version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: lab_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: