# ?????? ??? ??????????? ? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/lab_db
spring.datasource.username=postgres
spring.datasource.password=user
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

logging.level.root=INFO
logging.level.ru.ssau.tk.pmi=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

server.port=8080

